export const AUTH_SERVICE = "AUTH_SERVICE"
export const IPG_SERVICE = "IPG_SERVICE"
export const MAIL_SERVICE = "MAIL_SERVICE"
export const PACKAGE_SERVICE = "PACKAGE_SERVICE"

export const REQUEST_TIMEOUT = 4000;
